### PR TITLE
Asignment 4

### PR DESCRIPTION
**Pull request by Sanchitanwar0007**
Assignment 4 completed
Screenshot (96)
Screenshot (95)

### CODE REVIEW

**Comment by ashokdv** [comment]
Screenshot (210)

**Comment by ashokdv** [comment]
Task1 was Perfect (format.html) and Comments were also understandable. Coming to Task2(image.html) alignment was missing. Attached the screenshot, Please check. Overall , It is clear and good.

**Comment by Sanchitanwar0007** [comment]
The alignment is looks correct in my display . Its shows same as above comment.

**Comment by ashokdv** [comment]
Might be it is displayed like that because of screen size !! I have a screen display of 15.6

**Pull request merged**
